/*WebSocket*/
export const BEGIN_REQUEST_AUTH = 'BEGIN_REQUEST_AUTH'
export const BEGIN_REQUEST_START_AUTH = 'BEGIN_REQUEST_START_AUTH'
export const BEGIN_REQUEST_ACCESS = 'BEGIN_REQUEST_ACCESS'
export const BEGIN_INIT = 'BEGIN_INIT'
export const BEGIN_AUTH_RESPONSE = 'BEGIN_AUTH_RESPONSE'
export const BEGIN_AUTH_FAILURE = 'BEGIN_AUTH_FAILURE'

export const CHANGE_FORM = 'CHANGE_FORM'
export const SET_AUTH = 'SET_AUTH'





